version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - echo Running tests for surefire junit
      - mvn test -f pom.xml -fn
reports:
 arn:aws:codebuild:ap-southeast-1:868224632833:report-group/group2-BDD: #surefire junit reports
   files:
     - '**/*'
   base-directory: 'target/surefire-reports/'
reports:
  arn:aws:codebuild:ap-southeast-1:868224632833:report-group/group2-BDD:
    files:
      - "target/surefire-reports/*.xml"
    file-format: "JUNITXML"
artifacts:
  files:
    - '**/*'