version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
reports:
  arn:aws:codebuild:ap-southeast-1:868224632833:project/group2-BDD-testing:
    files:
      - "target/surefire-reports/*.xml"
    file-format: "CUCUMBERJSON"
artifacts:
  files:
    - '**/*'